@startuml
class CompletedItems{
CheckBoxTableCell checkBoxTableCell
TableColumn checkBoxColumn
==
.. Get the Checked Completed Items ..
+ TableColumn getCheckedComplete()
.. Set The Completed Items ..
+ void setCheckedComplete()
}

@enduml