@startuml
class ShowAll{
TableColumn tableColumn
CheckBoxTableCell checkBoxTableCell
==
.. Get Unchecked Column ..
+ TableColumn getUncheckedComplete()
.. Set Unchecked Column ..
+ void setUncheckedComplete()
}

@enduml