@startuml
class ShowAll{
public TableView tableView
public TextField txtboxTitle
private Button btnEdit
private CheckBoxTableCell deleteCheck
private CheckBoxTableCell checkCheck
==
.. Button Showing All Completed Items ..
+ showCompletedItems(ActionEvent actionEvent)
.. Button Showing All Uncompleted Items ..
+ showUncompleted(ActionEvent actionEvent)
.. Button to add New Items ..
+ addNewItem(ActionEvent actionEvent)
.. Button to delete Items ..
+ deleteNewItem(ActionEvent actionEvent)
.. Button To Save All Items ..
+ saveAllItems(ActionEvent actionEvent)
.. Button to load All Items ..
+ loadAllItems(ActionEvent actionEvent)
.. Button to show All Items ..
+ showAllItems(ActionEvent actionEvent)
.. Button to edit Title Name ..
+ editTitleName(ActionEvent inputMethodEvent)
}

@enduml